swagger: '2.0'
info:
  title: hello-world-node api-gateway-google-node
  description: Sample API on API Gateway with a Google Cloud Functions backend
  version: 1.0.0
schemes:
  - https
produces:
  - application/json
paths:
  /hellonode:
    get:
      summary: Greet a user
      operationId: hello
      x-google-backend:
        address: https://us-central1-ac-godafoss-dev.cloudfunctions.net/helloGET
      responses:
        '200':
          description: A successful response
          schema:
            type: string
